# The name of the snowflake account (e.g. xy12345.east-us-2.azure)
snowflake-account: {{ env_var('SNOWFLAKE_ACCOUNT') }}

# The name of the snowflake user
snowflake-user: {{ env_var('SCHEMACHANGE_USER') }}

# The name of the default role to use. can be overrideen in the change scripts.
snowflake-role: {{ env_var('SCHEMACHANGE_ROLE') }}

# The name of the default warehouse to use. Can be overridden in the change scripts.
snowflake-warehouse: {{ env_var('SCHEMACHANGE_WAREHOUSE') }}

# The name of the default warehouse to use. Can be overridden in the change scripts
snowflake-database: {{ env_var('SCHEMACHANGE_DATABASE') }}

# Used to override the default name of the change history table (the default is METADATA.SCHEMACHANGE.CHANGE_HISTORY)
change-history-table: {{ env_var('SCHEMACHANGE_DATABASE') }}.SCHEMACHANGE.CHANGE_HISTORY

# Create the change history schema and table, if they do not exist (the default is False)
create-change-history-table: true

# Enable autocommit feature for DML commands (the default is False)
autocommit: false

# Display verbose debugging details during execution (the default is False)
verbose: false

# Run schemachange in dry run mode (the default is False)
dry-run: false

# A string to include in the QUERY_TAG that is attached to every SQL statement executed
query-tag: 'Running schemachange'

# The root folder for the database changed scripts
root-folder: {{ env_var('SCHEMACHANGE_ROOT_FOLDER') }}

# The modules folder for Jinja macros and templates to be used across multiple scripts
modules-folder: src/modules